config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:       "users/sessions",
    registrations:  "users/registrations",
    passwords:      "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :tweets, only: [:index, :new, :create, :destroy]
  root to: 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_one_attached :avatar

  validates :name_or_username, presence: true
  validates :email, presence: true
  validates :name, :email, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         # :confirmable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.find_for_twitter_oauth(auth)
    user = User.find_by(:provider => auth.provider, :uid => auth.uid)
    unless user
      user = User.create( username: auth.info.name,
                          provider: auth.provider,
                          uid:      auth.uid,
                          email:    User.create_unique_email,
                          password: Devise.friendly_token[0,20]
                         )
    end
    user
  end

  # 通常サインアップ時のuid用、Twitter OAuth認証時のemail用にuuidな文字列を生成
  def self.create_unique_string
   SecureRandom.uuid
  end

  # twitterではemailを取得できないので、適当に一意のemailを生成
  def self.create_unique_email
   User.create_unique_string + "@example.com"
  end

  private
    def name_or_username
      name.presence || username.presence
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? #deviseで生成したファイルのみに適用する

  def after_sign_in_path_for(resource)
    tweets_path if resource.kind_of?(User)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.where(user_id: current_user.id).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
  end

  private
    def tweet_params
      params.require(:tweet).permit(:title, :content)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"].except("extra"))
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in_and_redirect @user, :event => :authentication
    else
      render new_user_registration_path
    end
  end

  def build_resource(hash=nil)
    if hash != nil
      hash[:uid] = User.create_unique_string
      super
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user
      sign_in_and_redirect @user, :event => :authentication
    else
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MitakalabTwitter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %h1.site-title mitakalab-twitter
      .nav
        - if user_signed_in?
          - if current_user.avatar.attached?
            = image_tag(current_user.avatar, size: '45x45')
          - else
            = image_tag('default_icon.png', size: '45x45')

          - if current_user.username
            %strong= current_user.username
          - else
            %strong= current_user.name

          = link_to 'Edit Profile', edit_user_registration_path
          = link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          = link_to 'Sign up', new_user_registration_path
          = link_to 'Login', new_user_session_path
    %p.notice= notice
    %p.alert= alert

    = yield

app/views/tops/index.html.haml
%h1 トップページです

app/views/tweets/destroy.html.haml
%p ツイートを削除しました
= link_to 'トップページヘ移動する', tweets_path

app/views/tweets/index.html.haml
= link_to 'つぶやく', new_tweet_path

- if @tweets.present?
  - @tweets.each do |tweet|
    %h3= tweet.title
    %p= tweet.content
    = link_to 'ツイートを削除する', tweet_path(tweet), method: :delete

= paginate @tweets

app/views/tweets/new.html.haml
= form_for @tweet do |f|
  = f.label :title
  = f.text_field :title
  = f.label :content
  = f.text_area :content
  = f.submit